<a href="https://colab.research.google.com/github/pedrocacioli/Exerc-cios/blob/main/S1D3_Tipos_de_Vari%C3%A1veis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("Fonte dos Dados.xlsx")
df.head()

,nomeLocalidade,estado,População residente,Densidade demográfica,Porcentagem de Jovens,Porcentagem de Ativos,Porcentagem de Idosos,Taxa de Urbanização,Taxa de Saneamento Básico,Ativos com Baixo Nível Educacional,...,Percentual de empresas do setor terciário em relação ao total,Percentual de trabalhadores do setor primário em relação ao total,Percentual de trabalhadores do setor secundário em relação ao total,Percentual de trabalhadores do setor terciário em relação ao total,Média Salarial,Produtividade,Taxa de desemprego dos jovens,Taxa de desemprego,"Número de trabalhadores(Comerciais, hotéis e restaurantes) por 1,000 habitantes","Número de ativos culturais e de lazer por 10,000 habitantes"
0,Acrelândia,Acre,12538,6.93,52.92,43.04,4.04,48.34,0.00,75.34,...,75.41,8.86,21.53,34.07,994.67,2654247.23,19.17,9.62,12.12,0.0
1,Assis Brasil,Acre,6072,1.22,55.58,40.07,4.35,65.30,2.39,66.83,...,100.00,0.60,0.00,36.25,1163.49,2113108.99,10.57,7.44,17.79,0.0
2,Brasiléia,Acre,21398,5.46,51.88,42.76,5.37,70.02,21.27,70.67,...,83.85,2.53,17.70,33.83,818.65,2376384.22,11.13,5.96,14.58,0.0
3,Bujari,Acre,8471,2.79,52.71,42.60,4.69,44.07,0.16,71.05,...,53.33,31.34,1.04,29.40,897.30,2668575.85,9.76,3.41,5.78,0.0
4,Capixaba,Acre,8798,5.17,53.92,41.92,4.16,44.60,0.82,77.90,...,62.50,4.30,30.37,10.32,843.49,2803488.37,6.35,4.14,7.73,0.0

In [ ]:
pd.pandas.set_option("display.max_columns", None)

In [ ]:
df.head()

,nomeLocalidade,estado,População residente,Densidade demográfica,Porcentagem de Jovens,Porcentagem de Ativos,Porcentagem de Idosos,Taxa de Urbanização,Taxa de Saneamento Básico,Ativos com Baixo Nível Educacional,Ativos com Médio Nível Educacional,Ativos com Alto Nível Educacional,Percentual de estrangeiros ao total de Trabalhadores,PIB Municipal,Estudantes Ensino primário,Estudantes Ensino secundário,Estudantes Ensino superior,Óbitos até 1 ano de idade por milhares de habitantes,Óbitos por milhares de habitantes,Nascidos por milhares de habitantes,Hospitais por milhares de habitantes,Médicos por milhares de habitantes,% de pobres,IDH,Percentual de trabalhadores especializados,"Valores de Importação por 10,000 habitantes","Valores de Exportação por 10,000 habitantes","Número de hotéis por 10,000 habitantes",Percentual de empresas do setor primário em relação ao total,Percentual de empresas do setor secundário em relação ao total,Percentual de empresas do setor terciário em relação ao total,Percentual de trabalhadores do setor primário em relação ao total,Percentual de trabalhadores do setor secundário em relação ao total,Percentual de trabalhadores do setor terciário em relação ao total,Média Salarial,Produtividade,Taxa de desemprego dos jovens,Taxa de desemprego,"Número de trabalhadores(Comerciais, hotéis e restaurantes) por 1,000 habitantes","Número de ativos culturais e de lazer por 10,000 habitantes"
0,Acrelândia,Acre,12538,6.93,52.92,43.04,4.04,48.34,0.00,75.34,19.52,5.14,0.08,1.221749e+08,3382,643,27,0.3,2.8,18.1,0.0,0.00,36.56,0.81,4.06,0.00,0.00,0.00,6.56,18.03,75.41,8.86,21.53,34.07,994.67,2654247.23,19.17,9.62,12.12,0.0
1,Assis Brasil,Acre,6072,1.22,55.58,40.07,4.35,65.30,2.39,66.83,26.93,6.23,14.19,4.205170e+07,2210,473,102,0.3,2.5,63.2,0.0,0.17,44.09,0.77,5.44,0.00,0.00,3.29,0.00,0.00,100.00,0.60,0.00,36.25,1163.49,2113108.99,10.57,7.44,17.79,0.0
2,Brasiléia,Acre,21398,5.46,51.88,42.76,5.37,70.02,21.27,70.67,21.29,8.04,2.00,1.906333e+08,4839,1297,309,0.1,4.2,25.0,0.0,0.14,35.22,0.77,8.55,14731.75,2119542.01,0.93,9.23,6.92,83.85,2.53,17.70,33.83,818.65,2376384.22,11.13,5.96,14.58,0.0
3,Bujari,Acre,8471,2.79,52.71,42.60,4.69,44.07,0.16,71.05,22.05,6.90,1.07,8.616439e+07,2348,487,53,0.4,0.5,21.0,0.0,0.00,37.61,0.77,5.52,0.00,0.00,0.00,40.00,6.67,53.33,31.34,1.04,29.40,897.30,2668575.85,9.76,3.41,5.78,0.0
4,Capixaba,Acre,8798,5.17,53.92,41.92,4.16,44.60,0.82,77.90,16.60,5.49,0.00,1.083468e+08,2539,327,37,0.1,0.8,16.8,0.0,0.00,35.00,0.79,5.30,0.00,93536.03,0.00,12.50,25.00,62.50,4.30,30.37,10.32,843.49,2803488.37,6.35,4.14,7.73,0.0

In [ ]:
df.shape

(5565, 40)

In [ ]:
print(f"o DataFrame possui {df.shape[0]} linhas e {df.shape[1]} colunas")

o DataFrame possui 5565 linhas e 40 colunas

In [ ]:
df.dtypes

nomeLocalidade                                                                      object
estado                                                                              object
População residente                                                                  int64
Densidade demográfica                                                              float64
Porcentagem de Jovens                                                              float64
Porcentagem de Ativos                                                              float64
Porcentagem de Idosos                                                              float64
Taxa de Urbanização                                                                float64
Taxa de Saneamento Básico                                                          float64
Ativos com Baixo Nível Educacional                                                 float64
Ativos com Médio Nível Educacional                                                 float64
Ativos com Alto Nível Educacional                                                  float64
Percentual de estrangeiros ao total de Trabalhadores                               float64
PIB Municipal                                                                      float64
Estudantes Ensino primário                                                           int64
Estudantes Ensino secundário                                                         int64
Estudantes Ensino superior                                                           int64
Óbitos até 1 ano de idade por milhares de habitantes                               float64
Óbitos por milhares de habitantes                                                  float64
Nascidos por milhares de habitantes                                                float64
Hospitais por milhares de habitantes                                               float64
Médicos por milhares de habitantes                                                 float64
% de pobres                                                                        float64
IDH                                                                                float64
Percentual de trabalhadores especializados                                         float64
Valores de Importação por 10,000 habitantes                                        float64
Valores de Exportação por 10,000 habitantes                                        float64
Número de hotéis por 10,000 habitantes                                             float64
Percentual de empresas do setor primário em relação ao total                       float64
Percentual de empresas do setor secundário em relação ao total                     float64
Percentual de empresas do setor terciário em relação ao total                      float64
Percentual de trabalhadores do setor primário em relação ao total                  float64
Percentual de trabalhadores do setor secundário em relação ao total                float64
Percentual de trabalhadores do setor terciário em relação ao total                 float64
Média Salarial                                                                     float64
Produtividade                                                                      float64
Taxa de desemprego dos jovens                                                      float64
Taxa de desemprego                                                                 float64
Número de trabalhadores(Comerciais, hotéis e restaurantes) por 1,000 habitantes    float64
Número de ativos culturais e de lazer por 10,000 habitantes                        float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5565 entries, 0 to 5564
Data columns (total 40 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   nomeLocalidade                                                                   5565 non-null   object
 1   estado                                                                           5565 non-null   object
 2   População residente                                                              5565 non-null   int64
 3   Densidade demográfica                                                            5565 non-null   float64
 4   Porcentagem de Jovens                                                            5565 non-null   float64
 5   Porcentagem de Ativos                                                            5565 non-null   float64
 6   Porcentagem de Idosos                                                            5565 non-null   float64
 7   Taxa de Urbanização                                                              5565 non-null   float64
 8   Taxa de Saneamento Básico                                                        5565 non-null   float64
 9   Ativos com Baixo Nível Educacional                                               5565 non-null   float64
 10  Ativos com Médio Nível Educacional                                               5565 non-null   float64
 11  Ativos com Alto Nível Educacional                                                5565 non-null   float64
 12  Percentual de estrangeiros ao total de Trabalhadores                             5565 non-null   float64
 13  PIB Municipal                                                                    5565 non-null   float64
 14  Estudantes Ensino primário                                                       5565 non-null   int64
 15  Estudantes Ensino secundário                                                     5565 non-null   int64
 16  Estudantes Ensino superior                                                       5565 non-null   int64
 17  Óbitos até 1 ano de idade por milhares de habitantes                             5565 non-null   float64
 18  Óbitos por milhares de habitantes                                                5565 non-null   float64
 19  Nascidos por milhares de habitantes                                              5565 non-null   float64
 20  Hospitais por milhares de habitantes                                             5565 non-null   float64
 21  Médicos por milhares de habitantes                                               5565 non-null   float64
 22  % de pobres                                                                      5565 non-null   float64
 23  IDH                                                                              5565 non-null   float64
 24  Percentual de trabalhadores especializados                                       5565 non-null   float64
 25  Valores de Importação por 10,000 habitantes                                      5565 non-null   float64
 26  Valores de Exportação por 10,000 habitantes                                      5565 non-null   float64
 27  Número de hotéis por 10,000 habitantes                                           5565 non-null   float64
 28  Percentual de empresas do setor primário em relação ao total                     5565 non-null   float64
 29  Percentual de empresas do setor secundário em relação ao total                   5565 non-null   float64
 30  Percentual de empresas do setor terciário em relação ao total                    5565 non-null   float64
 31  Percentual de trabalhadores do setor primário em relação ao total                5565 non-null   float64
 32  Percentual de trabalhadores do setor secundário em relação ao total              5565 non-null   float64
 33  Percentual de trabalhadores do setor terciário em relação ao total               5565 non-null   float64
 34  Média Salarial                                                                   5565 non-null   float64
 35  Produtividade                                                                    5565 non-null   float64
 36  Taxa de desemprego dos jovens                                                    5565 non-null   float64
 37  Taxa de desemprego                                                               5565 non-null   float64
 38  Número de trabalhadores(Comerciais, hotéis e restaurantes) por 1,000 habitantes  5565 non-null   float64
 39  Número de ativos culturais e de lazer por 10,000 habitantes                      5565 non-null   float64
dtypes: float64(34), int64(4), object(2)
memory usage: 1.7+ MB